### ISSUE TITLE
Proposal: Don't auto-refresh blocks page

### ISSUE THREAD

**Issue by deelawn** [onbloc/gnoscan#107]
I think the UX could be improved by not automatically reloading the latest blocks when browsing the https://gnoscan.io/blocks page.  It makes it impossible to continue loading blocks by clicking the button at the bottom of the list; the auto-reload will reset the list's state.

**Comment by dongwon8247** [comment]
Thank you for your suggestion, Dylan. 
I get your point. We will fix this as soon as possible.

**Comment by dongwon8247** [comment]
Should be fixed now. Let us know if it occurs again. Thank you!
