### ISSUE TITLE
Search By Returns Internal Server Error If Address Value Is Provided

### ISSUE THREAD

**Issue by nir1218** [onbloc/gnoscan#93]
If an account address is provided in the search box and then the search icon is clicked there is an internal server error with a blank page.
If the address is found then it should take to the account page, if the address is not found it should take the user to the search not found page.

**Comment by dongwon8247** [comment]
@nir1218 Thank you for the report, we will fix it as soon as possible.

**Comment by dongwon8247** [comment]
The issue should be resolved by now. Thank you!
