### ISSUE TITLE
Proposal: Add link to Gno Studio Connect

### ISSUE THREAD

**Issue by ilgooz** [onbloc/gnoscan#94]
In a detail page of a realm such as https://gnoscan.io/realms/details?path=gno.land/r/test10/poll, we can add connections to Gno Studio.

1-
Add a new section/button that says: "Interact on gno.studio".
The link for this button will be as: https://gno.studio/connect/view/gno.land/r/test10/poll?network=test3

2-
Add links to each function listed, for ex.:
Vote: https://gno.studio/connect/view/gno.land/r/test10/poll?network=test3#Vote
Render: https://gno.studio/connect/view/gno.land/r/test10/poll?network=test3#Render

<img width="483" alt="image" src="https://github.com/onbloc/gnoscan/assets/6023117/20219f09-becf-4ac2-becf-63e7e798bff9">

**Comment by ilgooz** [comment]
@salmad3

**Comment by dongwon8247** [comment]
@ilgooz Thank you for this great suggestion. We will add this when we work on GnoScan in late April or early May. cc @jinoosss

**Comment by dongwon8247** [comment]
Closed as completed via #95
